services:
  - type: web
    name: fashionecom-backend
    env: node
    region: singapore
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        value: vttul4cf
      - key: VITE_CLOUDINARY_CLOUD_NAME
        value: vttul4cf
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        sync: false
